version: 2

models:

  - name: access1-0_rcp45
    description: Zonal statistics for access1-0_rcp45 climatology

  - name: access1-0_rcp85
    description: Zonal statistics for access1-0_rcp85 climatology

  - name: bnu-esm_rcp26
    description: Zonal statistics for bnu-esm_rcp26 climatology

  - name: bnu-esm_rcp45
    description: Zonal statistics for bnu-esm_rcp45 climatology

  - name: ccsm4_rcp60
    description: Zonal statistics for ccsm4_rcp60 climatology

  - name: union_table
    description: Combination of all available climatologies

    columns:
      - name: objectid_1
        description: Unique identifier for an adm2
        tests:
            - not_null

      - name: admin0Name
        description: Country name
        tests:
            - not_null

      - name: admin0Pcod
            - not_null

      - name: admin1Name
        description: First administrative division name
        tests:
            - not_null

      - name: admin2Name
        description: Second administrative division name
        tests:
            - not_null

      - name: admin1Pcod
        description: Unique identifier for adm1

      - name: admin2Pcod
        description: Unique identifier for adm2

      - name: source
        description: Source of administrative division

      - name: last_modif
        description: Date that administrative division was last modified

      - name: date
        description: Date that administrative division was last modified
        tests:
            - not_null

      - name: min
        description: Minimum temperature in degrees Celsius
        tests:
            - not_null
        
      - name: max
        description: Maximum temperature in degrees Celsius
        tests:
            - not_null

      - name: mean
        description: Average temperature in degrees Celsius
        tests:
            - not_null

      - name: median
        description: Median temperature in degrees Celsius
        tests:
            - not_null

      - name: month
        description: Month of the year, in integer format (1-12)
        tests:
            - not_null