"""change id column type, add median_raw

Revision ID: a23eff8ce309
Revises: 42b5a33459ef
Create Date: 2023-08-16 15:50:26.382713

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a23eff8ce309"
down_revision: Union[str, None] = "42b5a33459ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bio", sa.Column("median_raw", sa.Float(), nullable=True))
    op.alter_column(
        "bio",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.add_column("prec", sa.Column("median_raw", sa.Float(), nullable=True))
    op.alter_column(
        "prec",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.add_column("temp", sa.Column("median_raw", sa.Float(), nullable=True))
    op.alter_column(
        "temp",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.add_column("tmax", sa.Column("median_raw", sa.Float(), nullable=True))
    op.alter_column(
        "tmax",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.add_column("tmin", sa.Column("median_raw", sa.Float(), nullable=True))
    op.alter_column(
        "tmin",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tmin",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("tmin", "median_raw")
    op.alter_column(
        "tmax",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("tmax", "median_raw")
    op.alter_column(
        "temp",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("temp", "median_raw")
    op.alter_column(
        "prec",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("prec", "median_raw")
    op.alter_column(
        "bio",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("bio", "median_raw")
    # ### end Alembic commands ###
