version: "3.9"
name: cmip-pipeline
services:
  pgdatabase:
    container_name: climate_postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - type: bind
        source: ${SOURCE}
        target: ${TARGET}
    ports:
      - "4000:5432"
    networks:
      - pg-network
  
  
  pgadmin:
    container_name: climate_pgadmin
    image: dpage/pgadmin4:6.19
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - pg-network

networks:
  pg-network:
    external: true

volumes:
  pgadmin_data:

    